// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsoc_top.h for the primary calling header

#ifndef VERILATED_VSOC_TOP___024ROOT_H_
#define VERILATED_VSOC_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vsoc_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsoc_top___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(jtag_tck,0,0);
        VL_OUT8(uart_tx,0,0);
        VL_IN8(uart_rx,0,0);
        VL_OUT8(spi_sclk,0,0);
        VL_OUT8(spi_mosi,0,0);
        VL_IN8(spi_miso,0,0);
        VL_OUT8(spi_cs_n,3,0);
        VL_OUT8(flash_sclk,0,0);
        VL_OUT8(flash_cs_n,0,0);
        VL_OUT8(flash_mosi,0,0);
        VL_IN8(flash_miso,0,0);
        VL_IN8(jtag_tms,0,0);
        VL_IN8(jtag_tdi,0,0);
        VL_OUT8(jtag_tdo,0,0);
        VL_OUT8(trap,0,0);
        CData/*0:0*/ soc_top__DOT__rst_ff1;
        CData/*0:0*/ soc_top__DOT__rst_ff2;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s0_awvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s0_awprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s0_wvalid;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__s0_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s0_bready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s0_arvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s0_arprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s0_rready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s1_awvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s1_awprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s1_wvalid;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__s1_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s1_bready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s1_arvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s1_arprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s1_rready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s2_awvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s2_awprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s2_wvalid;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__s2_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s2_bready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s2_arvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s2_arprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s2_rready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s3_awvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s3_awprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s3_wvalid;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__s3_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s3_bvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s3_bready;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__s3_bresp;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s3_arvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__s3_arprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s3_rvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__s3_rready;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__s3_rresp;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__apb_psel;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__apb_penable;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__apb_pwrite;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__apb_pstrb;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__apb_pprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__apb_pslverr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__psel_uart;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__psel_timer;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__psel_gpio;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__psel_spi;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__psel_debug;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__dbg_halted;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__jdbg_valid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__jdbg_write;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__jdbg_addr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__jdbg_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__trace_valid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__mem_valid;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__mem_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__mem_instr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__pcpi_valid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__axi_adapter__DOT__ack_awvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__axi_adapter__DOT__ack_arvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__axi_adapter__DOT__ack_wvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__axi_adapter__DOT__xfer_done;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_ready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_read;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_write;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_halt_req;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_resume_req;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__reg_sh;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__irq_delay;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__irq_active;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_halt_allowed;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__ebreak_halt_trigger;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_state;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_wordsize;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_prefetch;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_rinst;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_rdata;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_wdata;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_xfer;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_secondword;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_firstword_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__last_mem_valid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__prefetched_high_word;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__clear_prefetched_high_word;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_done_raw;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lui;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_auipc;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_jal;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_jalr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_beq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bne;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_blt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bge;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bltu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bgeu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lh;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lw;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lbu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lhu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sh;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sw;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_addi;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_slti;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sltiu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_xori;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_ori;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_andi;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_slli;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_srli;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_srai;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_add;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sub;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sll;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_slt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sltu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_xor;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_srl;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sra;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_or;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_and;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdcycle;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdcycleh;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdinstr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdinstrh;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_ecall_ebreak;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_fence;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_getq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_setq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_retirq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_maskirq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_waitirq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__instr_timer;
        CData/*5:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_rd;
        CData/*5:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_rs1;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_rs2;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoder_trigger;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoder_trigger_q;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoder_pseudo_trigger;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoder_pseudo_trigger_q;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__compressed_instr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_lui_auipc_jal;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_lb_lh_lw_lbu_lhu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_slli_srli_srai;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_sb_sh_sw;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_sll_srl_sra;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_lui_auipc_jal_jalr_addi_add_sub;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_slti_blt_slt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_sltiu_bltu_sltu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_beq_bne_blt_bge_bltu_bgeu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_lbu_lhu_lw;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_alu_reg_imm;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_alu_reg_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_compare;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_insn_rs1;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_insn_rs2;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_insn_rd;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_rs1val_valid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_rs2val_valid;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__q_insn_rs1;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__q_insn_rs2;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__q_insn_rd;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_next;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__launch_next_insn;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_valid_insn;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cached_insn_rs1;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cached_insn_rs2;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cached_insn_rd;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cpu_state;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__irq_state;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__set_mem_do_rinst;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__set_mem_do_rdata;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__set_mem_do_wdata;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_store;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_stalu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_branch;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_compr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_trace;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_is_lu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_is_lh;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_is_lb;
        CData/*5:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__latched_rd;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_timeout_counter;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_timeout;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__do_waitirq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_out_0;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_out_0_q;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_wait;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_wait_2;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_eq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_ltu;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_lts;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__clear_prefetched_high_word_q;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT____VdfgRegularize_had7d1046_0_1;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m0_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m0_axi_wvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m0_axi_bready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m0_axi_arvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m0_axi_rready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_awready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_wvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_wready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_bvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_arready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_rvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__w_active;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__r_active;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__w_sel_hold;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__r_sel_hold;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_awready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_wready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_bvalid;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_bresp;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_arready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_rvalid;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_rresp;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_awvalid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_wvalid;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_bready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_arvalid;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_arprot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_rready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s0_axi_awready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s0_axi_wready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s0_axi_arready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s1_axi_awready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s1_axi_wready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s1_axi_arready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s2_axi_awready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s2_axi_wready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__s2_axi_arready;
    };
    struct {
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__aw_slave_sel;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__ar_slave_sel;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__aw_decerr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__ar_decerr;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__w_state;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__w_slave_reg;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__w_prot_reg;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__r_state;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__r_slave_reg;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__r_prot_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_bootrom__DOT__rvalid_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_bootrom__DOT__aw_done;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_bootrom__DOT__w_done;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_bootrom__DOT__bvalid_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__sram_csb0;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__sram_web0;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__sram_wmask0;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__aw_captured;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__w_captured;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__bvalid_r;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__wr_pending;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__w_strb_r;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__rd_state;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__rd_access;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_enable;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_xip_en;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_addr_width;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_cmd;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_cmd_start;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_txdata;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_dummy_cycles;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__state;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__clk_phase;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__bit_cnt;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__shift_out;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__shift_in;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__byte_cnt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__rx_data_valid;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__rx_data_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__timeout_err;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__sclk_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__cs_n_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__mosi_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__r_valid_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__aw_done_r;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__w_done_r;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__bvalid_r;
        CData/*5:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__aw_addr_captured;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_aw_done;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_w_done;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_bvalid_r;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_rvalid_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_read_pending;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__clk_tick;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__axi_awready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__axi_wready;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__axi_arready;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__state;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__aw_captured;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__w_captured;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__aw_prot_reg;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__w_strb_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__apb_slverr_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__is_write_txn;
    };
    struct {
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_apb_xbar__DOT__slave_sel;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__tx_en;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__rx_en;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__irq_en;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__rx_overrun;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__frame_err_sticky;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__wr_ctrl_pulse;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__baud_tick;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__baud_tick_16x;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__baud_sub_cnt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__tx_fifo_wr_en;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__tx_fifo_wr_data;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__tx_start;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__tx_data_out;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__rx_data_in;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__rx_valid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__frame_error;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx_fifo__DOT__full;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx_fifo__DOT__empty;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx_fifo__DOT__wr_ptr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx_fifo__DOT__rd_ptr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx_fifo__DOT__wr_en;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx_fifo__DOT__full;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx_fifo__DOT__empty;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx_fifo__DOT__wr_ptr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx_fifo__DOT__rd_ptr;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx__DOT__state;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx__DOT__shift_reg;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx__DOT__bit_cnt;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx__DOT__state;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx__DOT__shift_reg;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx__DOT__bit_cnt;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx__DOT__sample_cnt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx__DOT__rx_sync_0;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx__DOT__rx_sync_1;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__ctrl_one_shot;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__ctrl_timer_size;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__ctrl_prescale;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__ctrl_int_en;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__ctrl_mode;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__ctrl_enable;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__raw_int;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__timer_stopped;
        CData/*7:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__prescale_counter;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__prescale_tick;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__load_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__bgload_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__ctrl_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__apb_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__apb_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__addr_valid;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT____VdfgRegularize_hf7b9a0fb_0_0;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_cpol;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_cpha;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_csid;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_csdef;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_csmode;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_endian;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_framelen;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_txmark;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_rxmark;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_ie;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_ip;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_enable;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_sw_rst;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__tx_wptr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__tx_rptr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__tx_count;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__rx_wptr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__rx_rptr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__rx_count;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__spi_state;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__clk_phase;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__bit_cnt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__sclk_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__mosi_reg;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__cs_setup_cnt;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__cs_hold_cnt;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__apb_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__apb_read;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__rx_pop;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__rx_push;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__out_bit_idx;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT____VdfgRegularize_h11c1cc39_0_0;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__bus_write;
        CData/*6:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__bus_addr;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__bus_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__dmactive;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__haltreq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__resumereq;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__dbg_halted_q;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__abstract_busy;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__cmderr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__dpc_written;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sbreadonaddr;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sbautoincrement;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sbreadondata;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sbbusyerror;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sberror;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sbaccess_size;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__resume_pending_q;
        CData/*2:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sba_state;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sba_start_read;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sba_start_write;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__aw_done;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__w_done;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sba_wstrb;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT____VdfgRegularize_h3902cce4_0_0;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT____VdfgRegularize_h3902cce4_0_1;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT____VdfgRegularize_h3902cce4_0_3;
        CData/*3:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__tap_state;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__ir_shift;
        CData/*4:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__ir_reg;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__bypass_reg;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_stat;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_busy;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_resp_op;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dtmcs_dmireset_pulse;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__update_dmi_d;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_write_tck;
        CData/*6:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_addr_tck;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__sync_ff1;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__sync_ff2;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__sync_ff3;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__resp_toggle_sys;
        CData/*1:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__resp_op_sys;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__resp_tog_sync1;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__resp_tog_sync2;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__resp_tog_last;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__resp_tck_pulse;
        CData/*0:0*/ soc_top__DOT__u_soc_core__DOT__u_irq_aggregator__DOT__timer_irq;
        CData/*2:0*/ __Vdly__soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__state;
        CData/*0:0*/ __Vdly__soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__aw_captured;
        CData/*0:0*/ __Vdly__soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__w_captured;
        CData/*3:0*/ __Vdly__soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__tap_state;
        CData/*0:0*/ __Vdly__soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__update_dmi_d;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__rst_ff2__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__jtag_tck__0;
        SData/*15:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_16bit_buffer;
        SData/*11:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__sram_addr0;
        SData/*11:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__aw_addr_r;
        SData/*15:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_clkdiv;
        SData/*15:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__clk_cnt;
        SData/*15:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__baud_div;
        SData/*15:0*/ soc_top__DOT__u_soc_core__DOT__u_uart__DOT__baud_counter;
        SData/*15:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__reg_sckdiv;
        SData/*15:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__clk_cnt;
        VL_IN(gpio_in,31,0);
        VL_OUT(gpio_out,31,0);
        VL_OUT(gpio_oe,31,0);
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__cpu_eoi;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s0_awaddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s0_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s0_araddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s1_awaddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s1_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s1_araddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s2_awaddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s2_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s2_araddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s3_awaddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s3_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s3_araddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__s3_rdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__apb_paddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__apb_pwdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__apb_prdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__prdata_gpio;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__prdata_spi;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__prdata_debug;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__jdbg_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__mem_addr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__mem_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__pcpi_insn;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT____Vlvbound_hc83e3f8d__0;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT____Vlvbound_h6f5e494c__0;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__reg_pc;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__reg_next_pc;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__reg_op1;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__reg_op2;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__reg_out;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__next_insn_opcode;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_insn_opcode;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_insn_addr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__next_pc;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__irq_mask;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__irq_pending;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__timer;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_halt_pc;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__i;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_rdata_word;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_rdata_q;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__mem_rdata_latched_noshuffle;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_imm;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_imm_j;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_insn_imm;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_rs1val;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_rs2val;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__q_insn_imm;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__q_insn_opcode;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cached_insn_imm;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cached_insn_opcode;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__irq_pending_ack;
        VlWide<4>/*127:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_ascii_state;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__current_pc;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__next_irq_pending;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_out;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__alu_out_q;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_wrdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_rs1;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_rs2;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m0_axi_rdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__m1_axi_rdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__x_rdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_awaddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__m_axi_araddr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__w_addr_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi_xbar__DOT__u_xbar__DOT__r_addr_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_bootrom__DOT__rdata_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_bootrom__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__sram_din0;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__sram_dout0;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__w_data_r;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__rdata_r;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_sram__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_addr;
        IData/*23:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__reg_jedec_id;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_read_buf;
        IData/*19:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__timeout_cnt;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__r_data_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_rdata_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_flash__DOT__xip_read_addr;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__aw_addr_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__w_data_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_axi2apb__DOT__apb_rdata_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_apb_xbar__DOT__prdata_timer;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__load_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__bgload_reg;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__counter;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_timer__DOT__counter_value;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_input_en;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_output_en;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_output_val;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_pue;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_ds;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_rise_ie;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_rise_ip;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_fall_ie;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_fall_ip;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_high_ie;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_high_ip;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_low_ie;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_low_ip;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_out_xor;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_iof_en;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__reg_iof_sel;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__sync_stage1;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__sync_stage2;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__sync_prev;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_gpio__DOT__strb_mask;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__shift_out;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_spi__DOT__shift_in;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__bus_wdata;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__data0;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__command;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__dpc_shadow;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__dcsr_shadow;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sbaddress0;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sbdata0;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_debug__DOT__sba_wdata_aligned;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__idcode_shift;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dtmcs_shift;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_resp_data;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_wdata_tck;
        IData/*31:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__resp_data_sys;
        IData/*31:0*/ __VactIterCount;
        QData/*35:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__trace_data;
        QData/*63:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__count_cycle;
        QData/*63:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__count_instr;
        QData/*63:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__new_ascii_instr;
        QData/*63:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__dbg_ascii_instr;
        QData/*63:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__q_ascii_instr;
        QData/*63:0*/ soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cached_ascii_instr;
        QData/*40:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_shift;
        QData/*40:0*/ soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_shift_rev;
        QData/*40:0*/ __Vdly__soc_top__DOT__u_soc_core__DOT__u_jtag_dtm__DOT__dmi_shift;
        VlUnpacked<IData/*31:0*/, 36> soc_top__DOT__u_soc_core__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs;
        VlUnpacked<IData/*31:0*/, 64> soc_top__DOT__u_soc_core__DOT__u_bootrom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 4096> soc_top__DOT__u_soc_core__DOT__u_sram__DOT__mem;
        VlUnpacked<CData/*7:0*/, 8> soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_tx_fifo__DOT__mem;
        VlUnpacked<CData/*7:0*/, 8> soc_top__DOT__u_soc_core__DOT__u_uart__DOT__u_rx_fifo__DOT__mem;
        VlUnpacked<IData/*31:0*/, 8> soc_top__DOT__u_soc_core__DOT__u_spi__DOT__tx_fifo;
        VlUnpacked<IData/*31:0*/, 8> soc_top__DOT__u_soc_core__DOT__u_spi__DOT__rx_fifo;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 7> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vsoc_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vsoc_top___024root(Vsoc_top__Syms* symsp, const char* namep);
    ~Vsoc_top___024root();
    VL_UNCOPYABLE(Vsoc_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
